version: '3.8'
services:
  embulk:
    container_name: embulk
    build:
      context: .
    volumes:
      - ./:/root
    tty: true
    stdin_open: true
  mysql:
    container_name: mysql
    image: mysql:5.7
    command:
      - --sql-mode=ALLOW_INVALID_DATES
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql-initdb.d:/docker-entrypoint-initdb.d
      # - ./mysql-data:/var/lib/mysql
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    # volumes:
    #   - es-data:/usr/share/elasticsearch/data